id: IC24E7D87
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:58:06+00:00'
last_modified: '2022-06-08T13:00:14.732816+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21763
  title: རྣལ་འབྱོར་གྱི་དབང་ཕྱུག་ཆེན་པོ་མི་ལ་རས་པའི་རྣམ་མགུར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0491:
      image_group_id: I4998
      title: ''
      total_pages: 913
      order: 1
      base_file: 0491.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
